export var element_personal = {
  messageModal: document.getElementById("modal-messagecode"),
  messageCode: document.getElementById("input_messagecode"),
  messageSendButton: document.getElementById("btn_send_messagecode"),
  messageSubmitButton: document.getElementById("btn_update_submit"),
  messageCancelButton: document.getElementById("modal-close-messagecode"),
  messageError: document.getElementById("errinfo_messagecode"),

  allPortraitWrap: document.getElementById("togglewrap-portrait"),
  portraitWord: document.getElementById("word-mask-portrait"),
  portraitBlackMask: document.getElementById("mask-portrait"),
  portrait: document.getElementById("img-personal-portrait"),
  portraitEditor: document.getElementById("mask-opacity-portrait"),
  portraitSaveEdit: document.getElementById("a_saveedit_portrait"),
  portraitCancelEdit: document.getElementById("a_canceledit_portrait"),

  nickname: document.getElementById("input-personal-nickname"),
  nicknameEditor: document.getElementById("a_editor_nickname"),
  nicknameSaveEdit: document.getElementById("a_saveedit_nickname"),
  nicknameCancelEdit: document.getElementById("a_canceledit_nickname"),
  nicknameError: document.getElementById("errinfo_nickname"),

  username: document.getElementById("input-personal-username"),
  usernameEditor: document.getElementById("a_editor_username"),
  usernameSaveEdit: document.getElementById("a_saveedit_username"),
  usernameCancelEdit: document.getElementById("a_canceledit_username"),
  usernameError: document.getElementById("errinfo_username"),

  password: document.getElementById("input-personal-password"),
  passwordEditor: document.getElementById("a_editor_password"),
  passwordSaveEdit: document.getElementById("a_saveedit_password"),
  passwordCancelEdit: document.getElementById("a_canceledit_password"),
  passwordError: document.getElementById("errinfo_password"),

  tel: document.getElementById("input-personal-tel"),
  telBind: document.getElementById("a_bind_tel"),
  telUnbind: document.getElementById("a_unbind_tel"),
  telSaveEdit: document.getElementById("a_saveedit_tel"),
  telCancelEdit: document.getElementById("a_cancelbind_tel"),
  telError: document.getElementById("errinfo_tel"),

  mail: document.getElementById("input-personal-mail"),
  mailBind: document.getElementById("a_bind_mail"),
  mailUnbind: document.getElementById("a_unbind_mail"),
  mailSaveEdit: document.getElementById("a_saveedit_mail"),
  mailCancelEdit: document.getElementById("a_cancelbind_mail"),
  mailError: document.getElementById("errinfo_mail"),

  wechat: document.getElementById("input-personal-wechat"),
  wechatBind: document.getElementById("a_bind_wechat"),
  wechatUnbind: document.getElementById("a_unbind_wechat"),
  wechatError: document.getElementById("errinfo_wechat"),

  qq: document.getElementById("input-personal-qq"),
  qqBind: document.getElementById("a_bind_qq"),
  qqUnbind: document.getElementById("a_unbind_qq"),
  qqSaveEdit: document.getElementById("a_saveedit_qq"),
  qqCancelEdit: document.getElementById("a_cancelbind_qq"),
  qqError: document.getElementById("errinfo_qq"),

  weibo: document.getElementById("input-personal-weibo"),
  weiboBind: document.getElementById("a_bind_weibo"),
  weiboUnbind: document.getElementById("a_unbind_weibo"),
  weiboSaveEdit: document.getElementById("a_saveedit_weibo"),
  weiboCancelEdit: document.getElementById("a_cancelbind_weibo"),
  weiboError: document.getElementById("errinfo_weibo"),

  totalTime: document.getElementById("span-mathpixtime"),
  currentTime: document.getElementById("progress-bar-remain"),
  maxTime: document.getElementById("progress-bar-max"),
  privateTime: document.getElementById("progress-bar-private"),
};
