export var element_login = {
  accountWrap: document.getElementById("wrap_account"),
  accountLoginName: document.getElementById("input_loginname"),
  accountLoginNameError: document.getElementById("errinfo_loginname"),
  accountLoginPassword: document.getElementById("input_loginpassword"),
  accountLoginPasswordError: document.getElementById("errinfo_loginpassword"),
  accountGVerify: document.getElementById("input_verify_code1"),
  accountGverifyError: document.getElementById("errinfo_verify_code1"),
  accountGVerifyCanvas: document.getElementById("canvan_verify_code1"),
  accountLoginButton: document.getElementById("btn_login_account"),
  accountToMessageButton: document.getElementById("a_gotomessage_account"),
  accountToRegButton: document.getElementById("a_gotoreg_account"),

  messageWrap: document.getElementById("wrap_messagecode"),
  messageCodeLoginTel: document.getElementById("input_logintel"),
  messageCodeLoginTelError: document.getElementById("errinfo_logintel"),
  messageCodeGVerify: document.getElementById("input_verify_code2"),
  messageCodeGverifyError: document.getElementById("errinfo_verify_code2"),
  messageCodeGVerifyCanvas: document.getElementById("canvan_verify_code2"),
  messageCodeCode: document.getElementById("input_loginmessagecode"),
  messageCodeCodeError: document.getElementById("errinfo_loginmessagecode"),
  messageCodeSendButton: document.getElementById("btn_send_message_verifycode"),
  messageCodeLoginButton: document.getElementById("btn_login_message"),
  messageCodeToAccountButton: document.getElementById("a_gotoaccount_messagecode"),
  messageCodeToRegButton: document.getElementById("a_gotoreg_messagecode"),

  regWrap: document.getElementById("wrap_reg"),
  regUsername: document.getElementById("input_regusername"),
  regUsernameError: document.getElementById("errinfo_regusername"),
  regPassword: document.getElementById("input_regpassword"),
  regPasswordError: document.getElementById("errinfo_regpassword"),
  regPasswordAgain: document.getElementById("input_regpasswordagain"),
  regPasswordAgainError: document.getElementById("errinfo_regpasswordagain"),
  regTel: document.getElementById("input_regtel"),
  regTelError: document.getElementById("errinfo_regtel"),
  regMail: document.getElementById("input_regmail"),
  regMailError: document.getElementById("errinfo_regmail"),
  regGVerify: document.getElementById("input_verify_code4"),
  regGverifyError: document.getElementById("errinfo_verify_code4"),
  regGverifyCanvas: document.getElementById("canvan_verify_code4"),
  regRegButton: document.getElementById("btn_reg"),
  regToAccountButton: document.getElementById("a_gotoaccount_reg"),
  regToMessageButton: document.getElementById("a_gotomessage_reg"),

  wxLoginButton: document.getElementById("a_wx_login"),
  qqLoginButton: document.getElementById("a_qq_login"),
  weiboLoginButton: document.getElementById("a_weibo_login"),
};
