document.writeln("<div id='isJavaScript'");
document.writeln("    style='width: 100%;height: 100%;position: absolute;z-index:3;top:0;left:0;background-color: #fff;display: block;'>");
document.writeln("    <div");
document.writeln("      style='width:60%;text-align: center;margin: 200px auto auto auto;padding:30px 50px 50px 50px;border: 1px solid rgba(0,0,0,0.2);border-radius: 0.25rem;'>");
document.writeln("      <img src='" + boot_body + "/img/favicon.png' style='text-align: center;position: relative; top:18px;margin-right: 15px;'><span");
document.writeln("        style='font-size: 20px;'>妈咪叔提醒您</span>");
document.writeln("      <h2 style='text-align: center;'>您的浏览器禁用了JavaScript</h2>");
document.writeln("      <p>要正常使用此WebAPP，请启用JavaScript，然后刷新页面</p>");
document.writeln("      <a href='http://aboutjavascript.com/en/how-to-enable-javascript-in-chrome.html'");
document.writeln("        target='_blank'>关于如何启用JavaScript，请戳这里</a>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("");
document.writeln("  <div id='ifIE-show'");
document.writeln("    style='width: 100%;height: 100%;position: absolute;z-index:3;top:0;left:0;background-color: #fff;display: none;'>");
document.writeln("    <div class='container'>");
document.writeln("      <div");
document.writeln("        style='width:60%;text-align: center;margin:60px auto 0 auto;padding:30px 50px 50px 50px;border: 1px solid rgba(0,0,0,0.2);border-radius: 0.25rem;'>");
document.writeln("        <img src='" + boot_body + "/img/favicon.png'");
document.writeln("          style='text-align: center;position: relative;margin-right: 15px;width: 40px;'><span");
document.writeln("          style='font-size: 20px;'>妈咪叔提醒您</span>");
document.writeln("        <h2 style='text-align: center;'>您的浏览器内核不支持此应用</h2>");
document.writeln("        <p>要正常使用此WebAPP，请使用支持此应用的浏览器，浏览器支持情况如下</p>");
document.writeln("        <img src='" + boot_body + "/img/browsers.png' style='width: 100%;'><br>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");

document.body.removeChild(document.getElementById("common_20"));
