document.writeln("<footer class='c' id='footer'>");
document.writeln("    <div class='container'>");
document.writeln("      <div class='contractme'>");
document.writeln("        <a href='mailto:info@latexlive.com' title='电子邮件'><i class='fa fa-envelope'></i></a>");
document.writeln("        <a href='https://weibo.com/mommytalkshow' target='_blank' title='新浪微博'><i class='fa fa-weibo'></i> </a>");
document.writeln("        <div id='wrap_wechat'>");
document.writeln("          <a href='##' id='a_wechat' title='微信公众号'>");
document.writeln("            <i class='fa fa-wechat'></i>");
document.writeln("          </a>");
document.writeln("          <div id='eqcode_wechat'>");
document.writeln("            <img src='' id='img_eqcode' />");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <a href='https://www.ixigua.com/home/62786280361/' target='_blank' title='西瓜视频'><img src='' id='img_toutiao' /></a>");
document.writeln("        <a href='https://gitee.com/yuetao_1011/la-te-xlive.git' target='_blank' title='码云'><img src='' id='img_gitee' /></a>");
document.writeln("        <a href='https://github.com/mommytalkltd/LaTeXLive.git' target='_blank' title='GitHub'><i class='fa fa-github'></i></a>");
document.writeln("        <a href='https://www.youtube.com/channel/UCLROLAN8kmU7tGQDs6KH-bQ?view_as=subscriber' target='_blank' title='油管'><i");
document.writeln("            class='fa fa-youtube'></i></a>");
document.writeln("      </div>");
document.writeln("      <div class='copyright'>");
document.writeln("        <p id='copyver'>Copyright &copy; 2019 妈咪说（北京）科技传媒有限公司 All Rights Reserved&nbsp;&nbsp;ver:1.3.0.200608</p>");
document.writeln("        <a href='https://beian.miit.gov.cn/' target='_blank'> <span>京ICP备19015398号-2</span> </a>&nbsp;&nbsp;");
document.writeln("        <a href='http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11011502004046' target='_blank'>");
document.writeln("          <img src='' id='img_police' />");
document.writeln("          <span>京公网安备 11011502004046号</span>");
document.writeln("        </a>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");

document.body.removeChild(document.getElementById("common_40"));
